"""Regression test — SSRF in /api/imports/preview via url hostname allowlist bypass

GENERATED by `aisec scan` from a finding a deterministic oracle verified against a
running target. Not hand-written, and not a model's judgment: every value below is
the request the oracle actually fired on.

    class      ssrf
    oracle     ssrf
    invariant  callback_server.was_contacted(nonce) is False
    evidence   POST /api/imports/preview made the target contact the listener at /probe/{{CALLBACK_URL}}
    source     routes/fetch.py:71

The assertion below is the SECURE invariant — what should hold once the bug is
fixed — so this file is a CI regression test, not a proof-of-exploit script. It
carries a strict xfail because the bug was live when it was generated:

    bug present -> assertion fails  -> xfail  -> `pytest .security-tests/` is GREEN
    bug fixed   -> assertion passes -> XPASS  -> RED, once, on the fixing commit

When it goes red, delete the `@pytest.mark.xfail` line. From then on it fails if
the bug ever comes back, which is the whole point of shipping it.

Requires the target to be running. Override the host with AISEC_TARGET_URL.
"""

from __future__ import annotations

import os
import time

import httpx
import pytest

from aisec.oracles import HttpObservation, OracleContext, check_ssrf


BASE_URL = os.environ.get("AISEC_TARGET_URL", "http://127.0.0.1:5001").rstrip("/")

METHOD = "POST"
PATH = "/api/imports/preview"
QUERY = ""
REQUEST_BODY = "{\"url\": \"{{CALLBACK_URL}}\"}"
SENT_AS = "alice"
OBSERVED_STATUS = 200


def _replay(request_body: str = REQUEST_BODY) -> HttpObservation:
    """Re-send the recorded request and observe it the way the scan did."""
    url = BASE_URL + PATH + (f"?{QUERY}" if QUERY else "")
    headers = {"Accept": "application/json, text/plain, */*"}
    if SENT_AS:
        # The tool layer chose this identity, not the model — see tools.http_request.
        headers["X-User"] = SENT_AS
    content = request_body.encode("utf-8") if request_body else b""
    if request_body:
        headers["Content-Type"] = "application/json"

    started = time.monotonic()
    with httpx.Client(timeout=10.0, follow_redirects=False) as client:
        response = client.request(METHOD, url, content=content, headers=headers)
    return HttpObservation.from_httpx(
        response,
        sent_as=SENT_AS,
        method=METHOD,
        path=PATH,
        query=QUERY,
        request_body=request_body,
        elapsed_ms=(time.monotonic() - started) * 1000,
    )


from aisec.callback import CallbackServer, mint_nonce
from aisec.tools import CALLBACK_TOKEN


def _verdict():
    """A fresh listener and a fresh nonce: the recorded probe URL is long dead.

    The oracle's attribution clause still holds — the nonce reaches the listener
    only if the target fetched it, because nothing else here can contact it.
    """
    with CallbackServer() as callback:
        nonce = mint_nonce()
        body = REQUEST_BODY.replace(CALLBACK_TOKEN, callback.url_for(nonce))
        if CALLBACK_TOKEN in REQUEST_BODY and body == REQUEST_BODY:  # pragma: no cover
            raise RuntimeError("callback token substitution failed")
        observation = _replay(body)
        callback.wait_for(nonce)
        return check_ssrf(
            [observation],
            OracleContext(callback_hits=callback.hits(), callback_nonce=nonce),
        )


VERDICT = _verdict()


@pytest.mark.xfail(strict=True, reason="ssrf bug live in the target when this test was generated")
def test_ssrf_api_imports_preview():
    assert not VERDICT.violated, (
        f"the target still fetches an attacker-supplied URL: {VERDICT.detail}"
    )
