"""Regression test — Path Traversal in GET /api/attachments/download - escaping data_root check

GENERATED by `aisec scan` from a finding a deterministic oracle verified against a
running target. Not hand-written, and not a model's judgment: every value below is
the request the oracle actually fired on.

    class      traversal
    oracle     traversal
    invariant  SECRET_CANARY not in response.text
    evidence   GET /api/attachments/download?filename=..%2Fprivate%2Fsecret-canary.txt returned the canary at byte 0
    source     routes/attachments.py:15

The assertion below is the SECURE invariant — what should hold once the bug is
fixed — so this file is a CI regression test, not a proof-of-exploit script. It
carries a strict xfail because the bug was live when it was generated:

    bug present -> assertion fails  -> xfail  -> `pytest .security-tests/` is GREEN
    bug fixed   -> assertion passes -> XPASS  -> RED, once, on the fixing commit

When it goes red, delete the `@pytest.mark.xfail` line. From then on it fails if
the bug ever comes back, which is the whole point of shipping it.

Requires the target to be running. Override the host with AISEC_TARGET_URL.
"""

from __future__ import annotations

import os
import time

import httpx
import pytest

from aisec.oracles import HttpObservation, OracleContext, check_path_traversal


BASE_URL = os.environ.get("AISEC_TARGET_URL", "http://127.0.0.1:5001").rstrip("/")

METHOD = "GET"
PATH = "/api/attachments/download"
QUERY = "filename=..%2Fprivate%2Fsecret-canary.txt"
REQUEST_BODY = ""
SENT_AS = "alice"
OBSERVED_STATUS = 200


def _replay(request_body: str = REQUEST_BODY) -> HttpObservation:
    """Re-send the recorded request and observe it the way the scan did."""
    url = BASE_URL + PATH + (f"?{QUERY}" if QUERY else "")
    headers = {"Accept": "application/json, text/plain, */*"}
    if SENT_AS:
        # The tool layer chose this identity, not the model — see tools.http_request.
        headers["X-User"] = SENT_AS
    content = request_body.encode("utf-8") if request_body else b""
    if request_body:
        headers["Content-Type"] = "application/json"

    started = time.monotonic()
    with httpx.Client(timeout=10.0, follow_redirects=False) as client:
        response = client.request(METHOD, url, content=content, headers=headers)
    return HttpObservation.from_httpx(
        response,
        sent_as=SENT_AS,
        method=METHOD,
        path=PATH,
        query=QUERY,
        request_body=request_body,
        elapsed_ms=(time.monotonic() - started) * 1000,
    )


import pathlib

CANARY_FILE = pathlib.Path(os.environ.get("AISEC_CANARY_FILE", "notes-app/data/private/secret-canary.txt"))


def _canary() -> str:
    """The canary is read from the target at runtime, never committed here."""
    if not CANARY_FILE.is_file():
        raise RuntimeError(
            f"canary file {CANARY_FILE} not found; set AISEC_CANARY_FILE to the "
            "target's private canary path"
        )
    text = CANARY_FILE.read_text(encoding="utf-8").strip()
    if len(text) < 8:
        raise RuntimeError(f"canary in {CANARY_FILE} is too short to be a signal")
    return text


def _verdict():
    observation = _replay()
    return check_path_traversal([observation], OracleContext(canary=_canary()))


VERDICT = _verdict()


@pytest.mark.xfail(strict=True, reason="traversal bug live in the target when this test was generated")
def test_traversal_api_attachments_download():
    assert not VERDICT.violated, (
        f"the target still serves the private canary file: {VERDICT.detail}"
    )
