"""Regression test — IDOR in GET /api/notes/<note_id> - missing ownership check

GENERATED by `aisec scan` from a finding a deterministic oracle verified against a
running target. Not hand-written, and not a model's judgment: every value below is
the request the oracle actually fired on.

    class      idor
    oracle     idor
    invariant  response.owner_id == requesting_user_id
    evidence   GET /api/notes/1002 as alice returned owner_id='bob'
    source     routes/notes.py:44

The assertion below is the SECURE invariant — what should hold once the bug is
fixed — so this file is a CI regression test, not a proof-of-exploit script. It
carries a strict xfail because the bug was live when it was generated:

    bug present -> assertion fails  -> xfail  -> `pytest .security-tests/` is GREEN
    bug fixed   -> assertion passes -> XPASS  -> RED, once, on the fixing commit

When it goes red, delete the `@pytest.mark.xfail` line. From then on it fails if
the bug ever comes back, which is the whole point of shipping it.

Requires the target to be running. Override the host with AISEC_TARGET_URL.
"""

from __future__ import annotations

import os
import time

import httpx
import pytest

from aisec.oracles import HttpObservation, OracleContext, check_idor


BASE_URL = os.environ.get("AISEC_TARGET_URL", "http://127.0.0.1:5001").rstrip("/")

METHOD = "GET"
PATH = "/api/notes/1002"
QUERY = ""
REQUEST_BODY = ""
SENT_AS = "alice"
OBSERVED_STATUS = 200


def _replay(request_body: str = REQUEST_BODY) -> HttpObservation:
    """Re-send the recorded request and observe it the way the scan did."""
    url = BASE_URL + PATH + (f"?{QUERY}" if QUERY else "")
    headers = {"Accept": "application/json, text/plain, */*"}
    if SENT_AS:
        # The tool layer chose this identity, not the model — see tools.http_request.
        headers["X-User"] = SENT_AS
    content = request_body.encode("utf-8") if request_body else b""
    if request_body:
        headers["Content-Type"] = "application/json"

    started = time.monotonic()
    with httpx.Client(timeout=10.0, follow_redirects=False) as client:
        response = client.request(METHOD, url, content=content, headers=headers)
    return HttpObservation.from_httpx(
        response,
        sent_as=SENT_AS,
        method=METHOD,
        path=PATH,
        query=QUERY,
        request_body=request_body,
        elapsed_ms=(time.monotonic() - started) * 1000,
    )


def _verdict():
    observation = _replay()
    return check_idor([observation], OracleContext(owner_field="owner_id"))


VERDICT = _verdict()


@pytest.mark.xfail(strict=True, reason="idor bug live in the target when this test was generated")
def test_idor_api_notes_1002():
    assert not VERDICT.violated, (
        f"cross-tenant read still works: {VERDICT.detail}"
    )
